apiVersion: v1
kind: Pod
metadata:
  name: custom-dns-pod
spec:
  containers:
  - name: test-container
    image: nginx
  dnsPolicy: "None" # Specifies that the DNS settings should be overridden.
  dnsConfig:
    nameservers:
      - "8.8.8.8" # Google's public DNS server
      - "8.8.4.4" # Secondary Google DNS server
    searches:
      - "ns1.svc.cluster.local"
      - "ns2.svc.cluster.local"
    options:
      - name: ndots
        value: "2"
      - name: edns0
