apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: exampleresources.mycompany.com
spec:
  group: mycompany.com
  names:
    kind: ExampleResource
    listKind: ExampleResourceList
    plural: exampleresources
    singular: exampleresource
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                size:
                  type: integer
